/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "app.h"
#include <cassert>

int main() {
    SystemMonitor::Greeter greeter;
    assert(greeter.greeting().compare("Hello, Muhammad Hassan Zahid!") == 0);
    return 0;
}
