/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"

std::string SystemMonitor::Greeter::greeting() {
    return std::string("Hello, Muhammad Hassan Zahid!");
}

int main () {
    SystemMonitor::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;

    return 0;
}